version: '3.8'

services:
  mqtt-broker_edgex:
    image: eclipse-mosquitto
    container_name: mqtt-broker_edgex
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - soa_net_edgex
    ports:
      - "1883:1883"


  gensensordata:
    build:
      context: ./genSensorData
      dockerfile: Dockerfile
    container_name: genSensorData
    networks:
      - soa_net_edgex
    depends_on:
      - mqtt-broker_edgex


  monitoring:
    build:
      context: ./Monitoring
      dockerfile: Dockerfile
    container_name: monitoring
    networks:
      - soa_net_edgex
    depends_on:
      - mqtt-broker_edgex

  visualization:
    build:
      context: ./Visualization/Visualization
      dockerfile: Dockerfile
    container_name: visualization
    networks:
      - soa_net_edgex
    depends_on:
      - mqtt-broker_edgex

  influxdb_edgex:
    image: influxdb:latest
    container_name: influxdb_edgex
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_ENABLED=true 
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-admin}
      - INFLUXDB_DB=prometheus
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_USER=${INFLUXDB_USER:-prometheus}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD:-prompass}
    ports:
      - "8086:8086"
    networks:
      - soa_net_edgex

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - soa_net_edgex
    depends_on:
      - influxdb_edgex
    environment:
      - GF_SECURITY_ADMIN_USER=$admin
      - GF_SECURITY_ADMIN_PASSWORD=$admin



networks:
  soa_net_edgex:
    driver: bridge
