global:
  # Kuiper home directory
  kuiper_home: "/kuiper"

  # Enable or disable console logging
  console_log: true

mqtt:
  broker:
    address: eclipse-mosquitto:1883
    username: "user3"
    password: "123"
    qos: 1

sources:
  - name: analitycsource
    type: mqtt
    format: json
    topics: ["ekupier/sensordata"]

rules:
  - name: myrule
    sql: SELECT * FROM mysource WHERE temp > 25
    actions:
      - mqtt:
          broker: eclipse-mosquitto:1883
          topic: "analyzed_sensordata"
