schema {
  query: Query
  mutation: Mutation
}

type Query{
    getAllReadings: [Reading]
}

type Reading {
    id: ID
    temperature: Float
    pH: Float
    turbidity: Float
    BOD: Float
    fecal: Float
    oxygen: Float
    nitr: Float
    conductivity: Float
}